language: java
jdk: oraclejdk8


before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install: mvn --settings travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true  -B -V


deploy:
  provider: script
  script: "mvn versions:set -DnewVersion=${TRAVIS_TAG} && mvn clean deploy -B -U -P release --settings travis/settings.xml"
  on:
    tags: true
