//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 09:52:47 PM NZDT 
//


package nz.co.senanque.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreferenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PreferenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="gluten"/>
 *     &lt;enumeration value="shellfish"/>
 *     &lt;enumeration value="lactose"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PreferenceType")
@XmlEnum
public enum PreferenceType {

    @XmlEnumValue("gluten")
    GLUTEN("gluten"),
    @XmlEnumValue("shellfish")
    SHELLFISH("shellfish"),
    @XmlEnumValue("lactose")
    LACTOSE("lactose");
    private final String value;

    PreferenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PreferenceType fromValue(String v) {
        for (PreferenceType c: PreferenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
